services:
  # Attribution Service
  - type: web
    name: ai-music-attribution-service
    env: python
    plan: free
    buildCommand: pip install -r attrib-service/requirements.txt
    startCommand: uvicorn app.attrib:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SUPABASE_URL
        value: https://ai-music-royalty-platform.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.supabase-anon-key-example
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.supabase-service-role-key-example
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-music-royalty-platform.vercel.app,http://localhost:3000
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000

  # Main API Service
  - type: web
    name: ai-music-main-api
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8001
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SUPABASE_URL
        value: https://ai-music-royalty-platform.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.supabase-anon-key-example
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.supabase-service-role-key-example
      - key: CORS_ALLOWED_ORIGINS
        value: https://ai-music-royalty-platform.vercel.app,http://localhost:3000
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8001
      - key: ADMIN_API_KEY
        value: ${ADMIN_API_KEY}
      - key: COMPLIANCE_SIGNING_SECRET
        value: ${COMPLIANCE_SIGNING_SECRET}
      - key: BLOCKCHAIN_ENABLED
        value: false
      - key: DEMO_MODE
        value: false
