name: CI

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint || echo "⚠️ Linting issues found (non-blocking)"

      - name: Build frontend
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-key' }}
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE || 'http://localhost:8001' }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: server/requirements.txt

      - name: Install backend dependencies
        run: |
          cd server
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd server
          pytest -q --tb=short || echo "⚠️ Tests failed (non-blocking)"
        continue-on-error: true

  security-check:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run npm audit
        run: npm audit --audit-level=high || echo "⚠️ Security vulnerabilities found"
        continue-on-error: true

      - name: Check for secrets
        run: |
          ! grep -r -E "(SUPABASE.*KEY|API.*KEY|SECRET|PASSWORD).*=.*['\"][\w-]{20,}" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.py" --exclude-dir=node_modules --exclude-dir=.next --exclude-dir=venv || echo "⚠️ Potential secrets found in code"
