name: Smoke
on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 7 * * *' # 07:00 UTC equals 09:00 Europe/Madrid
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check Main API health
        run: |
          set -e
          code=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.MAIN_API_URL }}/health")
          test "$code" = "200"
      - name: Check Main API version
        run: |
          set -e
          curl -fsSL "${{ secrets.MAIN_API_URL }}/version" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$"
      - name: Check Attribution API health
        run: |
          set -e
          code=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.ATTR_API_URL }}/health")
          test "$code" = "200"
      - name: Check Attribution API version
        run: |
          set -e
          curl -fsSL "${{ secrets.ATTR_API_URL }}/version" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$"
