name: Smoke
on:
  workflow_dispatch:
  push:
    branches: ['main']
  schedule:
    - cron: '0 7 * * *'

env:
  MAIN: ${{ secrets.MAIN_API_URL }}
  ATTR: ${{ secrets.ATTR_API_URL }}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Main /health
        run: |
          url="$MAIN/health"
          echo "GET $url"
          code=$(curl -sS -o /dev/null -w "%{http_code}" "$url")
          echo "HTTP $code"
          if [ "$code" -lt 200 ] || [ "$code" -ge 300 ]; then
            echo "Health check failed"; exit 1; fi
      - name: Main /version
        run: |
          url="$MAIN/version"
          echo "GET $url"
          body=$(curl -sS "$url" | tr -d '\r\n"' )
          echo "Body: $body"
          echo "$body" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || { echo "Bad version"; exit 1; }
      - name: Attrib /health
        run: |
          url="$ATTR/health"
          echo "GET $url"
          code=$(curl -sS -o /dev/null -w "%{http_code}" "$url")
          echo "HTTP $code"
          if [ "$code" -lt 200 ] || [ "$code" -ge 300 ]; then
            echo "Health check failed"; exit 1; fi
      - name: Attrib /version
        run: |
          url="$ATTR/version"
          echo "GET $url"
          body=$(curl -sS "$url" | tr -d '\r\n"' )
          echo "Body: $body"
          echo "$body" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || { echo "Bad version"; exit 1; }
